# Generated by Django 3.0.5 on 2020-05-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='default-hammer.jpg', upload_to='images/', verbose_name='ProductImage'),
        ),
    ]
