# Generated by Django 3.0.5 on 2020-05-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200526_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(verbose_name='Auction end date'),
        ),
    ]
